### DISCUSSION TITLE
CI/CD integration advice, possibly through official docker containers?

### DISCUSSION THREAD

**Discussion by MattyRad** [jacobdeichert/mask#119] [Q&A]
Hi, this is great!

I'd like to introduce mask to our CI/CD, but obtaining a mask executable inside of a random container is difficult. Certainly I could commit the binary to the repos, but that's a bit of a faux pas (you'd need to commit the binary to all *n* repos).

Enter docker. True, it seems like docker is a needless step when a binary is already offered, but the perk of docker is primarily that it can quickly provide a binary and also resolve architectures for you.

I was thinking that artifacts would be used to mount the binary in foreign containers, in Gitlab CI it might be something like:

```yaml
mask:
  stage: build
  image: some_mask_image
  needs: []
  script:
    -  cp /path/to/binary/mask .
  artifacts:
    paths:
      - mask

npm:
  stage: build
  image: node:18
  needs: ["mask"]
  script:
    - mask npm
```

I'm not 100% sure this is a good approach either, true be told. But it seems like it might be better than committing binaries to version control. Thoughts or advice on this approach, or how to integrate mask into CI/CD in general?
